version: "3"

services:
  app:
  container_name: api
  ports:
    -5000:5000
  restart: on-failure
  environnement:
    @MYSQL_DATABASE: "epytodo"configs:
    MYSQL_USER: "poc"
    MYSQL_PASSWORD: "poc"
  networks:
    -epytodo

volumes:
  mysql-data:

networks:
  epytodo:
